services:
  postgres:
    image: "postgres:12.19"
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
